from __future__ import annotations

import math
from datetime import date
from typing import Iterable

from .schemas import CircuitGate


def _sorted_ops(circuit: Iterable[CircuitGate]) -> list[CircuitGate]:
    return sorted(
        [gate for gate in circuit if gate.role != "tgt"],
        key=lambda gate: (gate.step, gate.qubit),
    )


def _ctrl_tgt(gate: CircuitGate) -> tuple[int, int]:
    ctrl = gate.ctrl if gate.ctrl is not None else max(0, gate.qubit - 1)
    tgt = gate.tgt if gate.tgt is not None else gate.qubit
    return ctrl, tgt


def generate_qiskit_code(circuit: list[CircuitGate], n_qubits: int) -> str:
    ops = _sorted_ops(circuit)
    today = date.today().isoformat()
    lines: list[str] = [
        f"# Auto-generated by Q-Edu · Qiskit · {today}",
        "from qiskit import QuantumCircuit, transpile",
        "from qiskit_aer import AerSimulator",
        "",
        f"# Initialize a {n_qubits}-qubit circuit",
        f"qc = QuantumCircuit({n_qubits}, {n_qubits})",
        "",
    ]
    if not ops:
        lines.append("# Circuit is empty. Add gate operations first")

    for gate in ops:
        ctrl, tgt = _ctrl_tgt(gate)
        if gate.g == "H":
            lines.append(f"qc.h({gate.qubit})  # step {gate.step}")
        elif gate.g == "X":
            lines.append(f"qc.x({gate.qubit})  # step {gate.step}")
        elif gate.g == "Y":
            lines.append(f"qc.y({gate.qubit})  # step {gate.step}")
        elif gate.g == "Z":
            lines.append(f"qc.z({gate.qubit})  # step {gate.step}")
        elif gate.g == "S":
            lines.append(f"qc.s({gate.qubit})  # step {gate.step}")
        elif gate.g == "T":
            lines.append(f"qc.t({gate.qubit})  # step {gate.step}")
        elif gate.g == "Rx":
            theta = math.radians(gate.p if gate.p is not None else 90.0)
            lines.append(f"qc.rx({theta:.6f}, {gate.qubit})  # step {gate.step}")
        elif gate.g == "Ry":
            theta = math.radians(gate.p if gate.p is not None else 90.0)
            lines.append(f"qc.ry({theta:.6f}, {gate.qubit})  # step {gate.step}")
        elif gate.g == "Rz":
            theta = math.radians(gate.p if gate.p is not None else 90.0)
            lines.append(f"qc.rz({theta:.6f}, {gate.qubit})  # step {gate.step}")
        elif gate.g == "CNOT":
            lines.append(f"qc.cx({ctrl}, {tgt})  # step {gate.step}")
        elif gate.g == "CZ":
            lines.append(f"qc.cz({ctrl}, {tgt})  # step {gate.step}")
        elif gate.g == "SWAP":
            lines.append(f"qc.swap({ctrl}, {tgt})  # step {gate.step}")
        elif gate.g == "M":
            lines.append(f"qc.measure({gate.qubit}, {gate.qubit})  # step {gate.step}")

    has_measure = any(gate.g == "M" for gate in ops)
    lines += [
        "",
        "# Run simulation",
    ]
    if not has_measure:
        lines.append("qc.measure_all()")
    lines += [
        "sim = AerSimulator()",
        "job = sim.run(transpile(qc, sim), shots=1024)",
        "counts = job.result().get_counts()",
        'print("Measurement results:", counts)',
    ]
    return "\n".join(lines)


def generate_mindquantum_code(circuit: list[CircuitGate], n_qubits: int) -> str:
    ops = _sorted_ops(circuit)
    today = date.today().isoformat()
    lines: list[str] = [
        f"# Auto-generated by Q-Edu · MindQuantum · {today}",
        "from mindquantum.core.circuit import Circuit",
        "from mindquantum.core.gates import H, X, Y, Z, S, T, CNOT, CZ, SWAP, RX, RY, RZ, Measure",
        "from mindquantum.simulator import Simulator",
        "",
        "circ = Circuit()",
    ]
    for gate in ops:
        ctrl, tgt = _ctrl_tgt(gate)
        if gate.g == "H":
            lines.append(f"circ += H.on({gate.qubit})")
        elif gate.g == "X":
            lines.append(f"circ += X.on({gate.qubit})")
        elif gate.g == "Y":
            lines.append(f"circ += Y.on({gate.qubit})")
        elif gate.g == "Z":
            lines.append(f"circ += Z.on({gate.qubit})")
        elif gate.g == "S":
            lines.append(f"circ += S.on({gate.qubit})")
        elif gate.g == "T":
            lines.append(f"circ += T.on({gate.qubit})")
        elif gate.g == "Rx":
            theta = math.radians(gate.p if gate.p is not None else 90.0)
            lines.append(f"circ += RX({theta:.6f}).on({gate.qubit})")
        elif gate.g == "Ry":
            theta = math.radians(gate.p if gate.p is not None else 90.0)
            lines.append(f"circ += RY({theta:.6f}).on({gate.qubit})")
        elif gate.g == "Rz":
            theta = math.radians(gate.p if gate.p is not None else 90.0)
            lines.append(f"circ += RZ({theta:.6f}).on({gate.qubit})")
        elif gate.g == "CNOT":
            lines.append(f"circ += CNOT.on({tgt}, {ctrl})")
        elif gate.g == "CZ":
            lines.append(f"circ += CZ.on({tgt}, {ctrl})")
        elif gate.g == "SWAP":
            lines.append(f"circ += SWAP.on([{ctrl}, {tgt}])")
        elif gate.g == "M":
            lines.append(f"circ += Measure({gate.qubit})")

    lines += [
        "",
        "print(circ)",
        f"sim = Simulator('mqvector', {n_qubits})",
        "sim.apply_circuit(circ)",
        "qs = sim.get_qs()",
        'print("Quantum state vector:", qs)',
    ]
    return "\n".join(lines)
